## Taller integrador

In [1]:
%pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/1f/67/af63f83cd6ca603a00fe8530c10a60f0879265b8be00b5930e8e78c5b30b/pandas-3.0.1-cp311-cp311-win_amd64.whl.metadata
  Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Obtaining dependency information for numpy>=1.26.0 from https://files.pythonhosted.org/packages/76/1d/edccf27adedb754db7c4511d5eac8b83f004ae948fe2d3509e8b78097d4c/numpy-2.4.3-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-2.4.3-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sra luz\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Obtaining dependency information for tzdata from https://files.pythonhosted.org/packages/c7/b0/003792df09decd6849a5e39c28b513c06e84436a54440380862b5aeff25d/tzdata-2025.3-py2.py3-none-any.whl.metadata
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\sra luz\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 991.0 kB/s eta 0:00:10
   -- ------------------------------------- 0.6/9.9 MB 7.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/9.9 MB 9.6 MB/s eta 0:00:01
   --------- ------------------------------ 2.2/9.9 MB 12.9 MB/s eta 0:00:01
   -------------- ------------------------- 3.7/9.9 MB 16.7 MB/s eta 0:00:01
   ---------------------- ----------------- 5.6/9.9 MB 22.2 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 27.1 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 30.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 27.5 MB/s eta 0:00:00
Downloading numpy-2.4.3-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------- ------------------------- 4.6/12.6 MB 143.0 MB/s eta 0:00:01
   --------------------------- ------------ 8.6/12.6 MB 109.3 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 93.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 65.5 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
   ---------------------------------------- 0.0/348.5 kB ? eta -:--:--
   --------------------------------------- 348.5/348.5 kB 21.1 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.3 pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

"print(pd.__version__)"

df = pd.read_csv("estudiantes.csv") 
df

    id            nombre  edad        ciudad  cursos_previos  promedio  activo
0    1       Laura Gómez    42      Medellín               0       8.3    True
1    2      Carlos Pérez    29          Cali               1       7.9    True
2    3        Anita Ruiz    40       Pereira               0       3.7    True
3    4       Juan Torres    29        Bogotá               8       4.8   False
4    5       María López    29     Manizales               4       8.8    True
5    6     Andrés Castro    27       Pereira               5       5.3    True
6    7     Sofía Herrera    32      Medellín               1       6.0    True
7    8    Diego Martínez    33     Cartagena               0       8.2    True
8    9    Valentina Ríos    34      Medellín               8       5.4    True
9   10       Felipe Mora    40  Barranquilla               1       3.8    True
10  11     Camila Vargas    31      Medellín               3       9.1   False
11  12    Sebastián Díaz    30     Manizales               5       4.6    True
12  13  Isabella Ramírez    28     Cartagena               1       7.5    True
13  14      Mateo Suárez    39  Barranquilla               2       6.5    True
14  15   Lucía Fernández    42  Barranquilla               5       9.0    True
15  16     Daniel Ortega    29        Bogotá               5       6.1    True
16  17  Gabriela Mendoza    28   Bucaramanga               3       7.8   False
17  18  Alejandro Flores    42     Manizales               2       5.2    True
18  19     Natalia Reyes    45     Cartagena               6       9.3   False
19  20     Ricardo Rojas    33  Barranquilla               2       6.8    True

Pandas -> Libreria Python
DataFrame -> Estructura que crea Pandas cuando carga un csv. Tiene por lo general filas y columnas

In [ ]:
# Shape devuelve (fila, columnas)
print(df.shape)

# Nombres exactos de las columnas
print(df.columns.tolist())

(20, 7)
['id', 'nombre', 'edad', 'ciudad', 'cursos_previos', 'promedio', 'activo']

In [8]:
# Imprime la linea que se le pide a la lista
df["nombre"]
#df["edad"]
#df["ciudad"]

0          Laura Gómez
1         Carlos Pérez
2           Anita Ruiz
3          Juan Torres
4          María López
5        Andrés Castro
6        Sofía Herrera
7       Diego Martínez
8       Valentina Ríos
9          Felipe Mora
10       Camila Vargas
11      Sebastián Díaz
12    Isabella Ramírez
13        Mateo Suárez
14     Lucía Fernández
15       Daniel Ortega
16    Gabriela Mendoza
17    Alejandro Flores
18       Natalia Reyes
19       Ricardo Rojas
Name: nombre, dtype: str

In [ ]:
# Para buscar un dato especifico de la lista
#print(df.loc[0, "nombre"])

#Para mostrar el ultimo nombre
print(df.loc[df.shape[0] -1, "nombre"])

Ricardo Rojas

In [ ]:
# Mostrar los primeros 5 datos de la tabla
df.head()

   id        nombre  edad     ciudad  cursos_previos  promedio  activo
0   1   Laura Gómez    42   Medellín               0       8.3    True
1   2  Carlos Pérez    29       Cali               1       7.9    True
2   3    Anita Ruiz    40    Pereira               0       3.7    True
3   4   Juan Torres    29     Bogotá               8       4.8   False
4   5   María López    29  Manizales               4       8.8    True

In [ ]:
# Metodo estadistico 
df.describe()

             id       edad  cursos_previos   promedio
count  20.00000  20.000000       20.000000  20.000000
mean   10.50000  34.100000        3.100000   6.705000
std     5.91608   5.901828        2.531902   1.814409
min     1.00000  27.000000        0.000000   3.700000
25%     5.75000  29.000000        1.000000   5.275000
50%    10.50000  32.500000        2.500000   6.650000
75%    15.25000  40.000000        5.000000   8.225000
max    20.00000  45.000000        8.000000   9.300000

In [ ]:
# Al momento de buscar datos en la tabla 
#df[(df["promedio"]>= 8.0)&(df["activo"] == True)]

# Se le agrega el nombre al final para que imprima solo los nombres de las personas que si cumplen con las condiciones
df[(df["promedio"] >= 8) & (df["activo"] == True)]["nombre"]

0         Laura Gómez
4         María López
7      Diego Martínez
14    Lucía Fernández
Name: nombre, dtype: str

### Limpiar dataSet pero con criterio

Detectar -> Hay algún problema?

In [20]:
# Importante cuando se llama a un metodo se encierra con ()
df.isnull().sum()

id                0
nombre            0
edad              0
ciudad            0
cursos_previos    0
promedio          0
activo            0
dtype: int64

### Se creo otro archivo para validar datos nulos

In [9]:
import pandas as pd

df = pd.read_csv("estudiantes_ml_2026_.csv") 
df

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
1,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
3,Jorge Ramírez,41,Lima,Perú,M,avanzado,6,7.4,2,True,2024-09-01,True,2100,emprendimiento
4,Daniela Soto,29,Santiago,Chile,F,intermedio,10,6.8,2,True,2024-09-01,True,1500,cambio de carrera
5,Miguel Flores,37,Guadalajara,México,M,básico,4,4.1,1,False,2024-09-01,True,900,ascenso laboral
6,Laura Gómez,31,Cali,Colombia,F,básico,11,7.9,2,True,2024-09-01,False,0,cambio de carrera
7,Sebastián Castro,26,Buenos Aires,Argentina,M,intermedio,14,8.3,3,True,2024-09-01,True,1100,emprendimiento
8,Camila Vargas,33,Quito,Ecuador,F,básico,9,6.1,2,True,2024-09-01,True,700,primer empleo tech
9,Andrés Herrera,45,Barranquilla,Colombia,M,avanzado,5,7.2,2,True,2024-09-01,True,2500,emprendimiento
10,Paula Jiménez,27,Montevideo,Uruguay,F,básico,13,8.5,3,True,2024-09-01,False,0,cambio de carrera
11,Ricardo López,39,Caracas,Venezuela,M,intermedio,7,5.8,1,True,2024-09-01,True,600,cambio de carrera
12,Isabella Martínez,24,Medellín,Colombia,F,básico,16,9.4,3,True,2024-09-01,False,0,primer empleo tech
13,Fernando Díaz,52,Bogotá,Colombia,M,avanzado,3,NaN,0,False,2024-09-01,True,3200,emprendimiento
14,Natalia Romero,30,Cartagena,Colombia,F,intermedio,11,7.6,2,True,2024-09-01,True,1300,cambio de carrera
15,Diego Morales,28,La Paz,Bolivia,M,básico,10,6.4,2,True,2024-09-01,True,500,primer empleo tech
16,Sofía Reyes,35,Ciudad de México,México,F,intermedio,8,7.1,2,True,2024-09-01,True,1400,ascenso laboral
17,Alejandro Núñez,23,Bogotá,Colombia,M,básico,18,9.2,3,True,2024-09-01,False,0,primer empleo tech
18,Mariana Castillo,43,Asunción,Paraguay,F,avanzado,6,6.9,2,True,2024-09-01,True,1800,emprendimiento
19,Luis Prada,31,Cúcuta,Colombia,M,básico,9,NaN,1,True,2024-09-01,True,750,ascenso laboral
20,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
21,Andrea Fuentes,26,Bogotá,Colombia,F,intermedio,12,8.1,3,True,2024-09-01,False,0,cambio de carrera
22,Tomás Aguirre,38,Córdoba,Argentina,M,avanzado,5,7.8,2,True,2024-09-01,True,1900,emprendimiento
23,Valeria Peña,29,Bucaramanga,Colombia,F,básico,14,8.9,3,True,2024-09-01,False,0,primer empleo tech
24,José Moreno,47,Ciudad de Panamá,Panamá,M,intermedio,4,5.5,1,True,2024-09-01,True,2200,ascenso laboral

In [11]:
df.head()

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
1,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
3,Jorge Ramírez,41,Lima,Perú,M,avanzado,6,7.4,2,True,2024-09-01,True,2100,emprendimiento
4,Daniela Soto,29,Santiago,Chile,F,intermedio,10,6.8,2,True,2024-09-01,True,1500,cambio de carrera

In [12]:
# Detectar espacios nulos
df.isnull().sum()

nombre                  0
edad                    0
ciudad                  0
pais                    0
genero                  0
nivel_previo            0
horas_estudio_semana    0
promedio                2
modulos_completados     0
activo                  0
fecha_ingreso           0
trabaja_actualmente     0
salario_usd             0
objetivo                0
dtype: int64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre                25 non-null     str
 1   edad                  25 non-null     int64
 2   ciudad                25 non-null     str
 3   pais                  25 non-null     str
 4   genero                25 non-null     str
 5   nivel_previo          25 non-null     str
 6   horas_estudio_semana  25 non-null     int64
 7   promedio              23 non-null     float64
 8   modulos_completados   25 non-null     int64
 9   activo                25 non-null     bool
 10  fecha_ingreso         25 non-null     str
 11  trabaja_actualmente   25 non-null     bool
 12  salario_usd           25 non-null     int64
 13  objetivo              25 non-null     str
dtypes: bool(2), float64(1), int64(4), str(7)
memory usage: 2.5 KB